name: dojo

dependencies:
- base >= 4.7 && < 5
- hspec
- QuickCheck

library:
  source-dirs: .

tests:
  dojo-test:
    main: Main.hs
    source-dirs: .
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dojo
